// <auto-generated />
using System;
using MT.Shop.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MT.Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MT.Shop.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(995);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(994);

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnOrder(992);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(997);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(996);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionCtrl")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(993);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("MT.Shop.Domain.Entities.Orders.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(995);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(994);

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnOrder(992);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(997);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(996);

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(4);

                    b.Property<byte[]>("VersionCtrl")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(993);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("MT.Shop.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(995);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(994);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(991);

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnOrder(992);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(997);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(996);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(3);

                    b.Property<byte[]>("VersionCtrl")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(993);

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 59,
                            Code = "10000001",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(2710),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 1",
                            Price = 45950000m
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 2,
                            Code = "10000002",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3914),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 2",
                            Price = 32620000m
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 106,
                            Code = "10000003",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3918),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 3",
                            Price = 92000000m
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 10,
                            Code = "10000004",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3920),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 4",
                            Price = 70060000m
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 58,
                            Code = "10000005",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3922),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 5",
                            Price = 70360000m
                        },
                        new
                        {
                            Id = 6,
                            AvailableStock = 36,
                            Code = "10000006",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3928),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 6",
                            Price = 21230000m
                        },
                        new
                        {
                            Id = 7,
                            AvailableStock = 47,
                            Code = "10000007",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3929),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 7",
                            Price = 65520000m
                        },
                        new
                        {
                            Id = 8,
                            AvailableStock = 84,
                            Code = "10000008",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3931),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 8",
                            Price = 37000000m
                        },
                        new
                        {
                            Id = 9,
                            AvailableStock = 65,
                            Code = "10000009",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3933),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 9",
                            Price = 23290000m
                        },
                        new
                        {
                            Id = 10,
                            AvailableStock = 55,
                            Code = "10000010",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3938),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 10",
                            Price = 97600000m
                        },
                        new
                        {
                            Id = 11,
                            AvailableStock = 14,
                            Code = "10000011",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3940),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 11",
                            Price = 43080000m
                        },
                        new
                        {
                            Id = 12,
                            AvailableStock = 35,
                            Code = "10000012",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3941),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 12",
                            Price = 7900000m
                        },
                        new
                        {
                            Id = 13,
                            AvailableStock = 119,
                            Code = "10000013",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3943),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 13",
                            Price = 5320000m
                        },
                        new
                        {
                            Id = 14,
                            AvailableStock = 96,
                            Code = "10000014",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3945),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 14",
                            Price = 36830000m
                        },
                        new
                        {
                            Id = 15,
                            AvailableStock = 95,
                            Code = "10000015",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3947),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 15",
                            Price = 39940000m
                        },
                        new
                        {
                            Id = 16,
                            AvailableStock = 40,
                            Code = "10000016",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3948),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 16",
                            Price = 28270000m
                        },
                        new
                        {
                            Id = 17,
                            AvailableStock = 24,
                            Code = "10000017",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3950),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 17",
                            Price = 550000m
                        },
                        new
                        {
                            Id = 18,
                            AvailableStock = 89,
                            Code = "10000018",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3953),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 18",
                            Price = 89230000m
                        },
                        new
                        {
                            Id = 19,
                            AvailableStock = 14,
                            Code = "10000019",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3955),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 19",
                            Price = 84400000m
                        },
                        new
                        {
                            Id = 20,
                            AvailableStock = 17,
                            Code = "10000020",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3957),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 20",
                            Price = 88260000m
                        },
                        new
                        {
                            Id = 21,
                            AvailableStock = 33,
                            Code = "10000021",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3958),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 21",
                            Price = 74660000m
                        },
                        new
                        {
                            Id = 22,
                            AvailableStock = 47,
                            Code = "10000022",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3960),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 22",
                            Price = 2840000m
                        },
                        new
                        {
                            Id = 23,
                            AvailableStock = 67,
                            Code = "10000023",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3962),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 23",
                            Price = 33970000m
                        },
                        new
                        {
                            Id = 24,
                            AvailableStock = 64,
                            Code = "10000024",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3964),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 24",
                            Price = 28820000m
                        },
                        new
                        {
                            Id = 25,
                            AvailableStock = 12,
                            Code = "10000025",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3965),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 25",
                            Price = 51810000m
                        },
                        new
                        {
                            Id = 26,
                            AvailableStock = 61,
                            Code = "10000026",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3967),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 26",
                            Price = 56250000m
                        },
                        new
                        {
                            Id = 27,
                            AvailableStock = 10,
                            Code = "10000027",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3969),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 27",
                            Price = 53560000m
                        },
                        new
                        {
                            Id = 28,
                            AvailableStock = 19,
                            Code = "10000028",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3971),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 28",
                            Price = 12990000m
                        },
                        new
                        {
                            Id = 29,
                            AvailableStock = 102,
                            Code = "10000029",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3972),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 29",
                            Price = 2560000m
                        },
                        new
                        {
                            Id = 30,
                            AvailableStock = 25,
                            Code = "10000030",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3974),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 30",
                            Price = 39730000m
                        },
                        new
                        {
                            Id = 31,
                            AvailableStock = 88,
                            Code = "10000031",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3976),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 31",
                            Price = 16030000m
                        },
                        new
                        {
                            Id = 32,
                            AvailableStock = 87,
                            Code = "10000032",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3978),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 32",
                            Price = 71500000m
                        },
                        new
                        {
                            Id = 33,
                            AvailableStock = 123,
                            Code = "10000033",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3980),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 33",
                            Price = 3150000m
                        },
                        new
                        {
                            Id = 34,
                            AvailableStock = 28,
                            Code = "10000034",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3983),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 34",
                            Price = 4490000m
                        },
                        new
                        {
                            Id = 35,
                            AvailableStock = 12,
                            Code = "10000035",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3995),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 35",
                            Price = 6320000m
                        },
                        new
                        {
                            Id = 36,
                            AvailableStock = 42,
                            Code = "10000036",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3997),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 36",
                            Price = 56020000m
                        },
                        new
                        {
                            Id = 37,
                            AvailableStock = 9,
                            Code = "10000037",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(3998),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 37",
                            Price = 26420000m
                        },
                        new
                        {
                            Id = 38,
                            AvailableStock = 25,
                            Code = "10000038",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4000),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 38",
                            Price = 40640000m
                        },
                        new
                        {
                            Id = 39,
                            AvailableStock = 119,
                            Code = "10000039",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4002),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 39",
                            Price = 77090000m
                        },
                        new
                        {
                            Id = 40,
                            AvailableStock = 40,
                            Code = "10000040",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4004),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 40",
                            Price = 58910000m
                        },
                        new
                        {
                            Id = 41,
                            AvailableStock = 104,
                            Code = "10000041",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4005),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 41",
                            Price = 27260000m
                        },
                        new
                        {
                            Id = 42,
                            AvailableStock = 67,
                            Code = "10000042",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4007),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 42",
                            Price = 85930000m
                        },
                        new
                        {
                            Id = 43,
                            AvailableStock = 127,
                            Code = "10000043",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4009),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 43",
                            Price = 45820000m
                        },
                        new
                        {
                            Id = 44,
                            AvailableStock = 115,
                            Code = "10000044",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4011),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 44",
                            Price = 43020000m
                        },
                        new
                        {
                            Id = 45,
                            AvailableStock = 102,
                            Code = "10000045",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4013),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 45",
                            Price = 86040000m
                        },
                        new
                        {
                            Id = 46,
                            AvailableStock = 29,
                            Code = "10000046",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4015),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 46",
                            Price = 23570000m
                        },
                        new
                        {
                            Id = 47,
                            AvailableStock = 57,
                            Code = "10000047",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4016),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 47",
                            Price = 6640000m
                        },
                        new
                        {
                            Id = 48,
                            AvailableStock = 67,
                            Code = "10000048",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4018),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 48",
                            Price = 23370000m
                        },
                        new
                        {
                            Id = 49,
                            AvailableStock = 109,
                            Code = "10000049",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4020),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 49",
                            Price = 37640000m
                        },
                        new
                        {
                            Id = 50,
                            AvailableStock = 70,
                            Code = "10000050",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4022),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 50",
                            Price = 87090000m
                        },
                        new
                        {
                            Id = 51,
                            AvailableStock = 95,
                            Code = "10000051",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4024),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 51",
                            Price = 29120000m
                        },
                        new
                        {
                            Id = 52,
                            AvailableStock = 105,
                            Code = "10000052",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4025),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 52",
                            Price = 12950000m
                        },
                        new
                        {
                            Id = 53,
                            AvailableStock = 8,
                            Code = "10000053",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4027),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 53",
                            Price = 13630000m
                        },
                        new
                        {
                            Id = 54,
                            AvailableStock = 80,
                            Code = "10000054",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4029),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 54",
                            Price = 39910000m
                        },
                        new
                        {
                            Id = 55,
                            AvailableStock = 4,
                            Code = "10000055",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4031),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 55",
                            Price = 13310000m
                        },
                        new
                        {
                            Id = 56,
                            AvailableStock = 76,
                            Code = "10000056",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4032),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 56",
                            Price = 85280000m
                        },
                        new
                        {
                            Id = 57,
                            AvailableStock = 95,
                            Code = "10000057",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4034),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 57",
                            Price = 76730000m
                        },
                        new
                        {
                            Id = 58,
                            AvailableStock = 19,
                            Code = "10000058",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4036),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 58",
                            Price = 18480000m
                        },
                        new
                        {
                            Id = 59,
                            AvailableStock = 114,
                            Code = "10000059",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4038),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 59",
                            Price = 66690000m
                        },
                        new
                        {
                            Id = 60,
                            AvailableStock = 89,
                            Code = "10000060",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4040),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 60",
                            Price = 78040000m
                        },
                        new
                        {
                            Id = 61,
                            AvailableStock = 47,
                            Code = "10000061",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4041),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 61",
                            Price = 3840000m
                        },
                        new
                        {
                            Id = 62,
                            AvailableStock = 57,
                            Code = "10000062",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4043),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 62",
                            Price = 90740000m
                        },
                        new
                        {
                            Id = 63,
                            AvailableStock = 115,
                            Code = "10000063",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4045),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 63",
                            Price = 15440000m
                        },
                        new
                        {
                            Id = 64,
                            AvailableStock = 71,
                            Code = "10000064",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4047),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 64",
                            Price = 73150000m
                        },
                        new
                        {
                            Id = 65,
                            AvailableStock = 97,
                            Code = "10000065",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4049),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 65",
                            Price = 69170000m
                        },
                        new
                        {
                            Id = 66,
                            AvailableStock = 39,
                            Code = "10000066",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4051),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 66",
                            Price = 27290000m
                        },
                        new
                        {
                            Id = 67,
                            AvailableStock = 3,
                            Code = "10000067",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4053),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 67",
                            Price = 51030000m
                        },
                        new
                        {
                            Id = 68,
                            AvailableStock = 111,
                            Code = "10000068",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4055),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 68",
                            Price = 42620000m
                        },
                        new
                        {
                            Id = 69,
                            AvailableStock = 62,
                            Code = "10000069",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4056),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 69",
                            Price = 43720000m
                        },
                        new
                        {
                            Id = 70,
                            AvailableStock = 92,
                            Code = "10000070",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4058),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 70",
                            Price = 30360000m
                        },
                        new
                        {
                            Id = 71,
                            AvailableStock = 49,
                            Code = "10000071",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4060),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 71",
                            Price = 74410000m
                        },
                        new
                        {
                            Id = 72,
                            AvailableStock = 27,
                            Code = "10000072",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4062),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 72",
                            Price = 27210000m
                        },
                        new
                        {
                            Id = 73,
                            AvailableStock = 115,
                            Code = "10000073",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4070),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 73",
                            Price = 20050000m
                        },
                        new
                        {
                            Id = 74,
                            AvailableStock = 56,
                            Code = "10000074",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4072),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 74",
                            Price = 540000m
                        },
                        new
                        {
                            Id = 75,
                            AvailableStock = 9,
                            Code = "10000075",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4074),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 75",
                            Price = 64970000m
                        },
                        new
                        {
                            Id = 76,
                            AvailableStock = 23,
                            Code = "10000076",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4076),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 76",
                            Price = 81800000m
                        },
                        new
                        {
                            Id = 77,
                            AvailableStock = 128,
                            Code = "10000077",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4077),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 77",
                            Price = 24550000m
                        },
                        new
                        {
                            Id = 78,
                            AvailableStock = 71,
                            Code = "10000078",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4079),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 78",
                            Price = 27160000m
                        },
                        new
                        {
                            Id = 79,
                            AvailableStock = 109,
                            Code = "10000079",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4081),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 79",
                            Price = 38160000m
                        },
                        new
                        {
                            Id = 80,
                            AvailableStock = 44,
                            Code = "10000080",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4083),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 80",
                            Price = 15780000m
                        },
                        new
                        {
                            Id = 81,
                            AvailableStock = 95,
                            Code = "10000081",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4084),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 81",
                            Price = 40170000m
                        },
                        new
                        {
                            Id = 82,
                            AvailableStock = 75,
                            Code = "10000082",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4086),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 82",
                            Price = 5770000m
                        },
                        new
                        {
                            Id = 83,
                            AvailableStock = 125,
                            Code = "10000083",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4088),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 83",
                            Price = 41260000m
                        },
                        new
                        {
                            Id = 84,
                            AvailableStock = 43,
                            Code = "10000084",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4090),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 84",
                            Price = 75240000m
                        },
                        new
                        {
                            Id = 85,
                            AvailableStock = 61,
                            Code = "10000085",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4174),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 85",
                            Price = 67080000m
                        },
                        new
                        {
                            Id = 86,
                            AvailableStock = 72,
                            Code = "10000086",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4177),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 86",
                            Price = 39110000m
                        },
                        new
                        {
                            Id = 87,
                            AvailableStock = 98,
                            Code = "10000087",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4178),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 87",
                            Price = 35100000m
                        },
                        new
                        {
                            Id = 88,
                            AvailableStock = 54,
                            Code = "10000088",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4180),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 88",
                            Price = 49130000m
                        },
                        new
                        {
                            Id = 89,
                            AvailableStock = 77,
                            Code = "10000089",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4182),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 89",
                            Price = 25530000m
                        },
                        new
                        {
                            Id = 90,
                            AvailableStock = 63,
                            Code = "10000090",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4183),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 90",
                            Price = 54680000m
                        },
                        new
                        {
                            Id = 91,
                            AvailableStock = 38,
                            Code = "10000091",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4185),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 91",
                            Price = 67280000m
                        },
                        new
                        {
                            Id = 92,
                            AvailableStock = 69,
                            Code = "10000092",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4187),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 92",
                            Price = 65590000m
                        },
                        new
                        {
                            Id = 93,
                            AvailableStock = 97,
                            Code = "10000093",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4189),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 93",
                            Price = 83820000m
                        },
                        new
                        {
                            Id = 94,
                            AvailableStock = 71,
                            Code = "10000094",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4190),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 94",
                            Price = 88560000m
                        },
                        new
                        {
                            Id = 95,
                            AvailableStock = 67,
                            Code = "10000095",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4192),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 95",
                            Price = 14800000m
                        },
                        new
                        {
                            Id = 96,
                            AvailableStock = 118,
                            Code = "10000096",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4194),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 96",
                            Price = 52790000m
                        },
                        new
                        {
                            Id = 97,
                            AvailableStock = 89,
                            Code = "10000097",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4197),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 97",
                            Price = 69820000m
                        },
                        new
                        {
                            Id = 98,
                            AvailableStock = 12,
                            Code = "10000098",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4199),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 98",
                            Price = 85330000m
                        },
                        new
                        {
                            Id = 99,
                            AvailableStock = 126,
                            Code = "10000099",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4201),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 99",
                            Price = 53470000m
                        },
                        new
                        {
                            Id = 100,
                            AvailableStock = 81,
                            Code = "10000100",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 762, DateTimeKind.Utc).AddTicks(4203),
                            IsActive = true,
                            IsDelete = false,
                            Name = "کالای 100",
                            Price = 73820000m
                        });
                });

            modelBuilder.Entity("MT.Shop.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(6);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(995);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(994);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnOrder(5);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnOrder(3);

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnOrder(992);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnOrder(4);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnOrder(997);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(996);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(7);

                    b.Property<byte[]>("VersionCtrl")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(993);

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tehran",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2024, 12, 14, 12, 23, 55, 760, DateTimeKind.Utc).AddTicks(6545),
                            Email = "rodbaran@Gmail.com",
                            FirstName = "حسین",
                            IsDelete = false,
                            LastName = "رودباران",
                            PhoneNumber = "09120753301"
                        });
                });

            modelBuilder.Entity("MT.Shop.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("MT.Shop.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MT.Shop.Domain.Entities.Orders.OrderDetail", b =>
                {
                    b.HasOne("MT.Shop.Domain.Entities.Orders.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MT.Shop.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MT.Shop.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
